[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin=lib/openzeppelin-contracts',
    'forge-std/=lib/forge-std/src/',
]
evm_version = 'london'
gas_reports = ['*']
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
fuzz_runs = 1024
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 14126430
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1643802347
block_difficulty = 0

